# Config options for the java generator
groupId: dev.pronk
artifactId: notificationapi-java-client
artifactDescription: Client for the NotificationAPI API
#artifactVersion: 1.0.0-SNAPSHOT
#generateApiTests: false
#generateModelTests: false
dateLibrary: java8
invokerPackage: dev.pronk.notificationapi.client.utils
modelPackage: dev.pronk.notificationapi.client.model
apiPackage: dev.pronk.notificationapi.client
java8: true
library: resteasy
hideGenerationTimestamp: true
useRuntimeException: true
useJakartaEe: false
developerEmail: pronk.arjan@gmail.com
developerName: Arjan Pronk
developerOrganization: None
developerOrganizationUrl: https://pronk.dev
scmConnection: scm:git:git@github.com:ArjanPronk/NotificationAPI-java-client.git
scmDeveloperConnection: scm:git:git@github.com:ArjanPronk/NotificationAPI-java-client.git
scmUrl: https://github.com/ArjanPronk/NotificationAPI-java-client

