/*
 * NotificationAPI api
 * ## 👋 Introduction  Welcome to the [NotificationAPI](https://notificationapi.com/) API Docs 🚀  ## 🛟 Help and support  We are gradually documenting our APIs 🐢 If you don't see something, just send us a message in the chat, and we'll get it updated in minutes 🐇  ## Glossary  - `envId` refers to the account or environment you are modifying - `user` refers to an end-user, the recipient of notifications - `member` refers to your team members with access to the dashboard - `notification` refers to a notification type that you configure in our dashboard, for example: `new_comment_notification`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pronk.dev.notificationapi.client;

import pronk.dev.notificationapi.client.utils.ApiException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * Client ID &amp; Client Secret Example
     *
     * Generally used for **server-to-server** connections where you have control over the client secret, for example, in your back-end.  This method uses the BASIC authorization model:  &#x60;&#x60;&#x60; Authorization: BASIC BASE64(\&quot;CLIENT_ID:CLIENT_SECRET\&quot;)   &#x60;&#x60;&#x60;  Example in JavaScript:  &#x60;&#x60;&#x60; javascript Authorization: Buffer.from(&#x60;${clientId}:${clientSecret}&#x60;).toString(\&quot;base64\&quot;)   &#x60;&#x60;&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void clientIdAuthValidateAuthenticateGetTest() throws ApiException {
        //
        //String clientId = null;
        //
        //api.clientIdAuthValidateAuthenticateGet(clientId);

        // TODO: test validations
    }
    /**
     * Client ID and User ID Secure Mode Example
     *
     * To prevent users from impersonating each other, you can enable secure mode ([learn more](https://docs.notificationapi.com/guides/secure-mode)). In secure mode, you need to append the user&#39;s hashedUserId to the string that is being encoded:  &#x60;&#x60;&#x60; Authorization: BASIC BASE64(\&quot;CLIENT_ID:USER_ID:HASHED_USER_ID\&quot;)   &#x60;&#x60;&#x60;  Example in JavaScript:  &#x60;&#x60;&#x60; javascript Authorization: BASIC Buffer.from(&#x60;${clientId}:${userId}:${hashedUserId}&#x60;).toString(\&quot;base64\&quot;)   &#x60;&#x60;&#x60;  To test secure mode correctly, you need to enable Secure Mode in your account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void clientIdUsersUserIdValidateUserGetTest() throws ApiException {
        //
        //String clientId = null;
        //
        //String userId = null;
        //
        //api.clientIdUsersUserIdValidateUserGet(clientId, userId);

        // TODO: test validations
    }
}
