/*
 * NotificationAPI api
 * ## 👋 Introduction  Welcome to the [NotificationAPI](https://notificationapi.com/) API Docs 🚀  ## 🛟 Help and support  We are gradually documenting our APIs 🐢 If you don't see something, just send us a message in the chat, and we'll get it updated in minutes 🐇  ## Glossary  - `envId` refers to the account or environment you are modifying - `user` refers to an end-user, the recipient of notifications - `member` refers to your team members with access to the dashboard - `notification` refers to a notification type that you configure in our dashboard, for example: `new_comment_notification`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pronk.dev.notificationapi.client;

import pronk.dev.notificationapi.client.utils.ApiException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SendingApi
 */
class SendingApiTest {

    private final SendingApi api = new SendingApi();

    /**
     * Delete a scheduled notification
     *
     * Deletes a notification that has been scheduled using the \&quot;scheduled\&quot; field.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void clientIdScheduleTrackingIdDeleteTest() throws ApiException {
        //
        //String clientId = null;
        //
        //String trackingId = null;
        //
        //String response = api.clientIdScheduleTrackingIdDelete(clientId, trackingId);

        // TODO: test validations
    }
    /**
     * Update a scheduled notification
     *
     * Update an already scheduled notification. The Request Body is similar to the Body when triggering the notification, but only with fields that you want to override or update.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void clientIdScheduleTrackingIdPatchTest() throws ApiException {
        //
        //String clientId = null;
        //
        //String trackingId = null;
        //
        //String contentType = null;
        //
        //Object body = null;
        //
        //String response = api.clientIdScheduleTrackingIdPatch(clientId, trackingId, contentType, body);

        // TODO: test validations
    }
    /**
     * Send a notification
     *
     * For a detailed description of parameters and options, visit [here](https://docs.notificationapi.com/reference/server#send).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void clientIdSenderPostTest() throws ApiException {
        //
        //String clientId = null;
        //
        //String contentType = null;
        //
        //String accept = null;
        //
        //Object body = null;
        //
        //api.clientIdSenderPost(clientId, contentType, accept, body);

        // TODO: test validations
    }
    /**
     * Delete In-App Notification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void envIdSenderRetractPostTest() throws ApiException {
        //
        //String envId = null;
        //
        //String contentType = null;
        //
        //Object body = null;
        //
        //String response = api.envIdSenderRetractPost(envId, contentType, body);

        // TODO: test validations
    }
}
