/*
 * NotificationAPI api
 * ## 👋 Introduction  Welcome to the [NotificationAPI](https://notificationapi.com/) API Docs 🚀  ## 🛟 Help and support  We are gradually documenting our APIs 🐢 If you don't see something, just send us a message in the chat, and we'll get it updated in minutes 🐇  ## Glossary  - `envId` refers to the account or environment you are modifying - `user` refers to an end-user, the recipient of notifications - `member` refers to your team members with access to the dashboard - `notification` refers to a notification type that you configure in our dashboard, for example: `new_comment_notification`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pronk.dev.notificationapi.client;

import pronk.dev.notificationapi.client.utils.ApiException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UndocumentedComponentsPublicUrlChannelApi
 */
class UndocumentedComponentsPublicUrlChannelApiTest {

    private final UndocumentedComponentsPublicUrlChannelApi api = new UndocumentedComponentsPublicUrlChannelApi();

    /**
     * /:envId/components_public_url/:channel
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void envIdComponentsPublicUrlChannelGetTest() throws ApiException {
        //
        //String envId = null;
        //
        //String channel = null;
        //
        //String accept = null;
        //
        //Object response = api.envIdComponentsPublicUrlChannelGet(envId, channel, accept);

        // TODO: test validations
    }
    /**
     * /:envId/components_public_url/:channel
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void envIdComponentsPublicUrlChannelOptionsTest() throws ApiException {
        //
        //String envId = null;
        //
        //String channel = null;
        //
        //String response = api.envIdComponentsPublicUrlChannelOptions(envId, channel);

        // TODO: test validations
    }
}
