/*
 * NotificationAPI api
 * ## 👋 Introduction  Welcome to the [NotificationAPI](https://notificationapi.com/) API Docs 🚀  ## 🛟 Help and support  We are gradually documenting our APIs 🐢 If you don't see something, just send us a message in the chat, and we'll get it updated in minutes 🐇  ## Glossary  - `envId` refers to the account or environment you are modifying - `user` refers to an end-user, the recipient of notifications - `member` refers to your team members with access to the dashboard - `notification` refers to a notification type that you configure in our dashboard, for example: `new_comment_notification`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package pronk.dev.notificationapi.client.utils;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.5.0")
public class Pair {
    private String name = "";
    private String value = "";

    public Pair (String name, String value) {
        setName(name);
        setValue(value);
    }

    private void setName(String name) {
        if (!isValidString(name)) {
            return;
        }

        this.name = name;
    }

    private void setValue(String value) {
        if (!isValidString(value)) {
            return;
        }

        this.value = value;
    }

    public String getName() {
        return this.name;
    }

    public String getValue() {
        return this.value;
    }

    private boolean isValidString(String arg) {
        if (arg == null) {
            return false;
        }

        return true;
    }
}
